import { ItemMenuPostRequestBody } from "./src/schema/menu.schema";

export const itensNobres: ItemMenuPostRequestBody[] = [
  { descricao: "Queijo à Milanesa", preco: 15.00 },
  { descricao: "Filé de Frango Crocante", preco: 18.00 },
  { descricao: "Bolinha de Queijo Massa de Macaxeira", preco: 15.00 },
  { descricao: "Batata Frita", preco: 18.00 },
  { descricao: "Macaxeira", preco: 15.00 },
  { descricao: "Pão de Alho Tradicional", preco: 7.00 },
  { descricao: "Bolinha de Carne de Sol Massa de Macaxeira", preco: 16.00 },
  { descricao: "Macaxeira c/ Queijo e Alho", preco: 19.00 },
  { descricao: "Batata Frita c/ Bacon e Cheddar", preco: 26.00 },
  { descricao: "Camarão Milanesa", preco: 27.00 },
  { descricao: "Camarão Alho e Óleo", preco: 32.00 },
  { descricao: "Carne de Sol c/ Macaxeira", preco: 40.00 },
  { descricao: "Filé Mignon Trinchado c/ Fritas", preco: 40.00 },
  { descricao: "Torresmo", preco: 10.00 },
  { descricao: "Moela ao Molho", preco: 13.00 },
  { descricao: "Espetinho Linguiça Mista Uni", preco: 3.50 },
  { descricao: "Espetinho Linguiça Apimentada", preco: 5.00 },
  { descricao: "Espetinho Coração de Frango", preco: 10.00 },
  { descricao: "Espetinho Queijo Coalho", preco: 8.00 },
  { descricao: "Espetinho Suíno", preco: 10.00 },
  { descricao: "Espetinho Frango Tulipa", preco: 10.00 },
  { descricao: "Espetinho Queijo Coalho c/ Melaço de Cana", preco: 9.00 },
  { descricao: "Espetinho Maminha", preco: 16.00 },
  { descricao: "Espetinho Medalhão de Frango", preco: 15.00 },
  { descricao: "Costelinha de Porco (100g)", preco: 8.00 },
  { descricao: "Chorizo Prime (100g)", preco: 11.00 },
  { descricao: "Maminha Importada (100g)", preco: 11.00 },
  { descricao: "Picanha Australiana (100g)", preco: 18.00 },
  { descricao: "A La Carte Costelinha Suína 400g (2 pessoas)", preco: 54.00 },
  { descricao: "A La Carte Carne de Sol 250g (2 pessoas)", preco: 57.00 },
  { descricao: "A La Carte Chorizo Prime 300g (2 pessoas)", preco: 65.00 },
  { descricao: "A La Carte Maminha Importada 400g (2 pessoas)", preco: 65.00 },
  { descricao: "A La Carte Picanha Australiana 400g (2 pessoas)", preco: 100.00 },
  { descricao: "Arroz Branco (P)", preco: 6.00 },
  { descricao: "Arroz Branco (G)", preco: 10.00 },
  { descricao: "Baião Tradicional (P)", preco: 7.00 },
  { descricao: "Baião Tradicional (G)", preco: 11.00 },
  { descricao: "Arroz de Leite (P)", preco: 7.00 },
  { descricao: "Arroz de Leite (G)", preco: 13.00 },
  { descricao: "Baião Cremoso (P)", preco: 8.00 },
  { descricao: "Baião Cremoso (G)", preco: 14.00 },
  { descricao: "Arroz à Grega (P)", preco: 9.00 },
  { descricao: "Arroz à Grega (G)", preco: 15.00 },
  { descricao: "Feijão Verde Cremoso", preco: 20.00 },
  { descricao: "Feijão Verde com Carne de Sol Desfiada", preco: 27.00 },
  { descricao: "Mini Churros Doce de Leite", preco: 15.00 },
  { descricao: "Pudim de Leite Condensado", preco: 10.00 },
  { descricao: "Cerveja Skol 600ml", preco: 10.50 },
  { descricao: "Cerveja Heineken 600ml", preco: 16.50 },
  { descricao: "Caipirinha", preco: 10.00 },
  { descricao: "Caipiroska", preco: 13.00 },
  { descricao: "Torre de Cerveja Skol 2,5L", preco: 35.00 },
  { descricao: "Suco de Acerola (Copo)", preco: 7.00 },
  { descricao: "Suco de Goiaba (Copo)", preco: 6.00 },
  { descricao: "Suco de Manga (Copo)", preco: 6.00 },
  { descricao: "Suco de Cajá (Copo)", preco: 7.00 },
  { descricao: "Suco de Graviola (Copo)", preco: 7.00 },
  { descricao: "Suco de Maracujá (Copo)", preco: 8.00 },
  { descricao: "Jarra de Suco de Polpa", preco: 16.00 },
  { descricao: "Limonada (Copo)", preco: 8.00 },
  { descricao: "Suco de Abacaxi (Copo)", preco: 8.00 },
  { descricao: "Suco de Laranja (Copo)", preco: 8.00 },
  { descricao: "Jarra de Suco Natural", preco: 18.00 },
  { descricao: "Coca-Cola 600ml", preco: 8.00 },
  { descricao: "Cajuína 600ml", preco: 8.00 },
  { descricao: "Coca-Cola Zero 1L", preco: 10.00 },
  { descricao: "Coca-Cola 1L", preco: 10.00 },
  { descricao: "Guaraná 1L", preco: 10.00 },
  { descricao: "Fanta Laranja 1L", preco: 10.00 },
  { descricao: "Cajuína 1L", preco: 10.00 },
  { descricao: "Coca-Cola KS", preco: 4.50 },
  { descricao: "Refrigerante Lata Cajuína", preco: 6.00 },
  { descricao: "Refrigerante Lata Coca-Cola", preco: 6.00 },
  { descricao: "Refrigerante Lata Coca-Cola Zero", preco: 6.00 },
  { descricao: "Refrigerante Lata Guaraná", preco: 6.00 },
  { descricao: "Refrigerante Lata Guaraná Zero", preco: 6.00 },
  { descricao: "Refrigerante Lata Fanta Laranja", preco: 6.00 },
  { descricao: "Refrigerante Lata Fanta Uva", preco: 6.00 },
  { descricao: "Refrigerante Lata Schwepps", preco: 6.00 },
  { descricao: "Refrigerante Lata Sprite", preco: 6.00 },
  { descricao: "Água s/ Gás", preco: 2.50 },
  { descricao: "Água c/ Gás", preco: 3.50 },
  { descricao: "Coco Verde", preco: 6.00 },
  { descricao: "Coco Jarra", preco: 12.00 },
  { descricao: "Água Tônica", preco: 5.00 },
  { descricao: "H2O Limão", preco: 7.00 },
  { descricao: "H2O Limoneto", preco: 6.00 },
  { descricao: "Cerveja Skol 600ml", preco: 10.50 },
  { descricao: "Cerveja Bohemia 600ml", preco: 11.00 },
  { descricao: "Cerveja Amstel 600ml", preco: 11.00 },
  { descricao: "Cerveja Brahma Duplo Malte 600ml", preco: 11.50 },
  { descricao: "Cerveja Budweiser 600ml", preco: 11.50 },
  { descricao: "Cerveja Spaten 600ml", preco: 12.50 },
  { descricao: "Cerveja Stella 600ml", preco: 13.50 },
  { descricao: "Cerveja Antártica Original 600ml", preco: 12.50 },
  { descricao: "Cerveja Heineken 600ml", preco: 16.50 },
  { descricao: "Long Neck Brahma Duplo Malte", preco: 8.00 },
  { descricao: "Long Neck Budweiser", preco: 9.00 },
  { descricao: "Long Neck Budweiser Zero Álcool", preco: 9.00 },
  { descricao: "Long Neck Stella", preco: 11.00 },
  { descricao: "Long Neck Spaten", preco: 10.00 },
  { descricao: "Long Neck Corona", preco: 11.00 },
  { descricao: "Long Neck Heineken", preco: 12.00 },
  { descricao: "Cabaré Ice", preco: 10.00 },
  { descricao: "Skol Beats Senses", preco: 11.00 },
  { descricao: "Smirnoff Ice", preco: 12.00 },
  { descricao: "Energético Monster", preco: 15.00 },
  { descricao: "Energético Redbull", preco: 13.00 },
  { descricao: "Conhaque Droher Dose", preco: 4.50 },
  { descricao: "Vodka Orloff Dose", preco: 6.50 },
  { descricao: "Vodka Smirnoff Dose", preco: 7.50 },
  { descricao: "Whisky Black White Dose", preco: 8.00 },
  { descricao: "Whisky Red Label Dose", preco: 11.00 },
  { descricao: "Whisky Ballantines Dose", preco: 11.00 },
  { descricao: "Whisky Cavalo Branco Dose", preco: 11.00 },
  { descricao: "Whisky Old Parr Dose", preco: 15.00 },
  { descricao: "Whisky Chivas Regal Dose", preco: 16.00 },
  { descricao: "Campari Dose", preco: 9.00 },
  { descricao: "Martini Bianco e Vermouth Dose", preco: 7.00 },
  { descricao: "Cachaça Ypioca Ouro (Dose)", preco: 4.50 },
  { descricao: "Cachaça Ypioca Mestre (Dose)", preco: 4.50 },
  { descricao: "Cachaça 51 Ouro (Dose)", preco: 4.50 },
  { descricao: "Cachaça 51 Seleção (Dose)", preco: 4.50 },
  { descricao: "Cachaça Ypioca 150 Anos (Dose)", preco: 9.00 },
  { descricao: "Cachaça Salina (Dose)", preco: 8.00 },
  { descricao: "Cachaça Matuta (Dose)", preco: 6.00 },
  { descricao: "Cachaça Ypioca Ouro (Terça)", preco: 8.00 },
  { descricao: "Cachaça Ypioca Mestre (Terça)", preco: 8.00 },
  { descricao: "Cachaça 51 Ouro (Terça)", preco: 8.00 },
  { descricao: "Cachaça 51 Seleção (Terça)", preco: 8.50 },
  { descricao: "Cachaça Ypioca 150 Anos (Terça)", preco: 25.00 },
  { descricao: "Cachaça Salina (Terça)", preco: 13.00 },
  { descricao: "Cachaça Matuta (Terça)", preco: 12.00 },
  { descricao: "Cachaça Ypioca Ouro (Burrinho)", preco: 10.00 },
  { descricao: "Cachaça Ypioca Mestre (Burrinho)", preco: 10.00 },
  { descricao: "Cachaça 51 Ouro (Burrinho)", preco: 10.00 },
  { descricao: "Cachaça 51 Seleção (Burrinho)", preco: 9.50 },
  { descricao: "Cachaça Ypioca 150 Anos (Burrinho)", preco: 27.00 },
  { descricao: "Cachaça Salina (Burrinho)", preco: 15.00 },
  { descricao: "Cachaça Matuta (Burrinho)", preco: 14.00 },
  { descricao: "Caipifruta", preco: 15.00 },
  { descricao: "Pina Colada", preco: 18.00 },
  { descricao: "Espanhola", preco: 19.00 },
  { descricao: "Gin Tônica", preco: 20.00 },
  { descricao: "Gin Citrus", preco: 22.00 },
  { descricao: "Gin Fruta", preco: 23.00 },
  { descricao: "Torre de Cerveja Budweiser 2,5L", preco: 37.00 }
]